In [4]:
import numpy as np

In [15]:
list_1 = np.arange(0,21,step = 1)
print(list_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
list_2 = np.arange(0,21,step = 2)
print(list_2)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [17]:
list_3 = np.arange(0,21,step = 3)
print(list_3)

[ 0  3  6  9 12 15 18]
